"""Initial migration with users, face_data, books, borrow_records

Revision ID: 6b44dfe627e1
Revises: 
Create Date: 2026-03-11 19:29:49.848165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b44dfe627e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False, comment='图书ID，主键'),
    sa.Column('isbn', sa.String(length=20), nullable=True, comment='ISBN编号'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='书名'),
    sa.Column('author', sa.String(length=100), nullable=False, comment='作者'),
    sa.Column('publisher', sa.String(length=100), nullable=True, comment='出版社'),
    sa.Column('publish_date', sa.DateTime(), nullable=True, comment='出版日期'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='图书分类'),
    sa.Column('description', sa.Text(), nullable=True, comment='图书简介'),
    sa.Column('cover_image', sa.String(length=255), nullable=True, comment='封面图片路径'),
    sa.Column('total_copies', sa.Integer(), nullable=False, comment='图书总册数'),
    sa.Column('available_copies', sa.Integer(), nullable=False, comment='可借阅册数'),
    sa.Column('location', sa.String(length=50), nullable=True, comment='存放位置'),
    sa.Column('status', sa.Enum('AVAILABLE', 'BORROWED', 'RESERVED', 'DAMAGED', 'LOST', name='bookstatus'), nullable=False, comment='图书状态'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.create_index(op.f('ix_books_category'), 'books', ['category'], unique=False)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户ID，主键'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名，唯一'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码，加密存储'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱地址，唯一'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像图片路径'),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False, comment='用户角色：admin-管理员, user-普通用户'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='账号是否激活'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('borrow_records',
    sa.Column('id', sa.Integer(), nullable=False, comment='借阅记录ID，主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='借阅用户ID，外键'),
    sa.Column('book_id', sa.Integer(), nullable=False, comment='借阅图书ID，外键'),
    sa.Column('borrow_date', sa.DateTime(), nullable=False, comment='借阅日期'),
    sa.Column('due_date', sa.DateTime(), nullable=False, comment='应还日期'),
    sa.Column('return_date', sa.DateTime(), nullable=True, comment='实际归还日期'),
    sa.Column('status', sa.Enum('BORROWED', 'RETURNED', 'OVERDUE', 'RENEWED', name='borrowstatus'), nullable=False, comment='借阅状态：borrowed-借阅中, returned-已归还, overdue-逾期, renewed-已续借'),
    sa.Column('renew_count', sa.Integer(), nullable=False, comment='续借次数'),
    sa.Column('fine_amount', sa.Float(), nullable=False, comment='罚款金额'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注信息'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrow_records_id'), 'borrow_records', ['id'], unique=False)
    op.create_table('face_data',
    sa.Column('id', sa.Integer(), nullable=False, comment='人脸数据ID，主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联的用户ID，外键'),
    sa.Column('face_encoding', sa.LargeBinary(), nullable=False, comment='人脸特征向量，二进制存储'),
    sa.Column('face_image_path', sa.String(length=255), nullable=True, comment='人脸照片存储路径'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_face_data_id'), 'face_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_face_data_id'), table_name='face_data')
    op.drop_table('face_data')
    op.drop_index(op.f('ix_borrow_records_id'), table_name='borrow_records')
    op.drop_table('borrow_records')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index(op.f('ix_books_category'), table_name='books')
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
